apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-deploy
  labels:
    app: student

spec:
  replicas: 1
  selector:
    matchLabels:
      app: student

  template:
    metadata:
      labels:
        app: student

    spec:
      containers:
      - name: student-container
        image: 506995420953.dkr.ecr.us-east-2.amazonaws.com/studentapp:latest
        ports:
        - name: student-port
          containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: student-service
  labels:
    app: student

spec:
  type: LoadBalancer
  selector:
    app: student

  ports:
  - name: student-port
    protocol: TCP
    port: 80
    targetPort: 8080
